Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -8,20 +8,21 @@ pipeline {
 		NEXUS_REG_IP='10.182.0.16'
 		NEXUS_REG_PORT=8082
 		DOCK_IMG_NAME="${NEXUS_REG_IP}:${NEXUS_REG_PORT}/appointme-admin-api:${BUILD_NUMBER}"
-                K8S_IMG_NAME="${NEXUS_REG_IP}:${NEXUS_REG_PORT}\\/appointme-admin-api:${BUILD_NUMBER}"
+    K8S_IMG_NAME="${NEXUS_REG_IP}:${NEXUS_REG_PORT}\/appointme-admin-api:${BUILD_NUMBER}"
 		date_format = new Date().format('dd-MM-yy-HHmm')
 			
-  }
+   }
 
   stages 
   {
     stage("Create Docker image") 
-      {
+    {
     
-      steps {
+        steps 
+          {
       
-        withCredentials([usernamePassword(credentialsId: 'nexus-secret', passwordVariable: 'pass', usernameVariable: 'username')]) 
-        {
+           withCredentials([usernamePassword(credentialsId: 'nexus-secret', passwordVariable: 'pass', usernameVariable: 'username')]) 
+            {
       
               sh '''
                 sudo docker build -t ${DOCK_IMG_NAME} .
@@ -29,44 +30,42 @@ pipeline {
                 sudo docker push ${DOCK_IMG_NAME}
                 
                 '''
-		     }
-
-       }
-    }
+		        }
+         }
+     }
        
   stage("Trivy Docker scan") 
   {
-    steps 
-    {
-     sh '''
+      steps 
+      {
+           sh '''
      
-	      sudo trivy image ${DOCK_IMG_NAME} 2>/dev/null |grep "Total: [0-9]" 
-	      for TH in `sudo trivy image ${DOCK_IMG_NAME} 2>/dev/null |grep "Total: [0-9]" |cut -d ":" -f7|cut -d ")" -f1`
-	      do
+	         sudo trivy image ${DOCK_IMG_NAME} 2>/dev/null |grep "Total: [0-9]" 
+	         for TH in `sudo trivy image ${DOCK_IMG_NAME} 2>/dev/null |grep "Total: [0-9]" |cut -d ":" -f7|cut -d ")" -f1`
+	         do
                   if [ -z "${TH}" ] || [ $TH -gt ${TRIVY_CRITICAL_THRES} ]
-	          then   
-	              echo "FAILED:Critical: "${TH} " has Crossed the Critical Threshold Limit of "${TRIVY_CRITICAL_THRES} !!!!!
-		      exit 1
-	          fi
-	      done
+	                then   
+	                  echo "FAILED:Critical: "${TH} " has Crossed the Critical Threshold Limit of "${TRIVY_CRITICAL_THRES} !!!!!
+		                exit 1
+	                fi
+	           done
 	      
 	      '''
  
-     }
+       }
     }  
 	     
    
 
-   stage("Deploy into Dev")
-   {
-    steps
-     {
-      sh '''
-
-      sed  's/<NEW_IMAGE_NAME>/'${DOCK_IMG_NAME}'/g' k8s-deploy-template.yml > k8-deploy.yaml
-      kubectl apply -f k8-deploy.yaml -n dev
-
-      ''' 
+    stage("Deploy into Dev")
+    {
+       steps
+       {
+          sh '''
+          sed  's/<NEW_IMAGE_NAME>/'${DOCK_IMG_NAME}'/g' k8s-deploy-template.yml > k8-deploy.yaml
+          kubectl apply -f k8-deploy.yaml -n dev
+          ''' 
+       }
      }
-   }
+  }
 }
